### PR TITLE
suggestion for modernization: no more 'stupid blonde' jokes

### PR DESCRIPTION
**Pull request by s0nata**

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @s0nata ! Sorry for the late reply, but I feel that this is the ["removing sesame seeds"](https://www.shlomifish.org/philosophy/foss-other-beasts/version-3/foss-and-other-beasts-v3/challenges_to_foss.xhtml#challenges__removing_sesame_seeds) syndrome so I'd rather not merge this PR. I'll leave it open for now so we can have a discussion about it (you can close it if you'd like).

**Comment by s0nata** [comment]
@shlomif, I see your point regarding deleting content, but I would still be in favour of not having those kind of jokes. Grew up with them, still makes me sad to see them pop out. How about substituting them with something more modern of approx same length?

**Comment by shlomif** [comment]
> @shlomif, I see your point regarding deleting content, but I would still be in favour of not having those kind of jokes. Grew up with them, still makes me sad to see them pop out. How about substituting them with something more modern of approx same length?

@s0nata : well, I was teased a lot as a kid and teenager for my last name - "Fish", and for other reasons, but now it's great because I can use the [EvilPHish emblem](https://www.shlomifish.org/meta/FAQ/#evilphish-emblem) as my user-pic. In one of my screenplays ["Kate" was getting teased](https://www.shlomifish.org/humour/Selina-Mandrake/ongoing-text.html#kate-tells-her-story) for having black/brown hair because she lived in England and some of her acquinatnces believed it was indicative of having a Jewish heritage.

Anyway, if it disturbs you so much, you can apply a local patch or try to get your OS vendor to apply a downstream patch. fortune-mod is [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) after all.

**Comment by s0nata** [comment]
@shlomif , this is not about me having to put up with jokes about my appearance at school. This is not about anybody being teased because they are Jewish or not. This is about perpetuating derogative stereotypes about a social group in a good thing FOSS is. This is about inclusion: software developers are not an elite 'boys club' anymore, women code too, and seeing less content of this kind helps to feel that we are equal part of the developer community.

**Comment by shlomif** [comment]
> @shlomif , this is not about me having to put up with jokes about my appearance at school. This is not about anybody being teased because they are Jewish or not. This is about perpetuating derogative stereotypes about a social group in a good thing FOSS is. This is about inclusion: software developers are not an elite 'boys club' anymore, women code too, and seeing less content of this kind helps to feel that we are equal part of the developer community.

Well, if you can redo the commit that:

1. The "off"ensive fortunes will not be touched - some downstream distributors disable them and they are only displayed with the `-o` flag or similar.

2. Move the offending fortunes to `/off/`.

then i'll apply it. BTW, see https://tech.slashdot.org/story/14/10/21/1852246/npr-80s-ads-are-responsible-for-the-lack-of-women-coders .

**Comment by shlomif** [comment]
@s0nata : ping.

**Comment by s0nata** [comment]
> Well, if you can redo the commit that:
> 
>     1. The "off"ensive fortunes will not be touched - some downstream distributors disable them and they are only displayed with the `-o` flag or similar.
> 
>     2. Move the offending fortunes to `/off/`.
> 
> 
> then i'll apply it. BTW, see https://tech.slashdot.org/story/14/10/21/1852246/npr-80s-ads-are-responsible-for-the-lack-of-women-coders .

That is actually a much greater solution, thank you for suggesting it! I'm on it, will update the pull request today.

**Comment by s0nata** [comment]
@shlomif how do the new changes look to you?

**Comment by shlomif** [comment]
> @shlomif how do the new changes look to you?

They look fine. I'll test and merge.

**Comment by shlomif** [comment]
Merged, thanks!

**Pull request merged**
