### PR TITLE
Added quote from Alexis Carrel.

### PR DESCRIPTION
**Pull request by telometto**

### CODE REVIEW

**Comment by telometto** [comment]
Added more quotes.

**Comment by shlomif** [comment]
@telometto : hi! nice quotes, thanks, but you need to rebase my master branch into yours. And in the future, use feature branches for your PRs.

**Comment by shlomif** [comment]
Also please fix the tests failures: https://app.travis-ci.com/github/shlomif/fortune-mod/builds/242100582

**Comment by telometto** [comment]
Oh, God. Wrong place to commit :(

**Comment by telometto** [comment]
How can I stop the build?

**Comment by shlomif** [comment]
> How can I stop the build?

I stopped it.

**Comment by shlomif** [comment]
@telometto hi! Any news? I'd really like to see these in.

**Comment by shlomif** [comment]
@telometto hi! FYI I merged the changes now. Thanks!

**Comment by telometto** [comment]
> @telometto hi! FYI I merged the changes now. Thanks!

Thanks, @shlomif 
I am new to git and, after a lot of headaches on trying to implementing the changes the way you asked me to, I had to give up. Sorry for the inconvenience but thanks for implementing them ^_^

**Pull request closed without merging**
