### PR TITLE
Added Shingeki no Kyojin quotes.

### PR DESCRIPTION
**Pull request by memepaleontologist2002**
Added some Attack on Titan quotes.

### CODE REVIEW

**Comment by shlomif** [comment]
@memepaleontologist2002 : first of all, the new files are not being installed. Secondly, the text lines are far too long.

**Comment by memepaleontologist2002** [comment]
I'll go work on that.

**Comment by shlomif** [comment]
> I'll go work on that. Should I create symlinks?

I think you should just add them here: https://github.com/shlomif/fortune-mod/blob/f04de9468dcf0dd58fec56c7efbd1a604ea2c2cc/fortune-mod/CMakeLists.txt#L289 . Thanks.

**Comment by memepaleontologist2002** [comment]
I used Eclipse to test the project, so I had to modify the .gitignore

**Comment by shlomif** [comment]
Hi @memepaleontologist2002 !

The test suite failed:

```
[00:02:58] Running [prove -v C:/projects/fortune-mod/fortune-mod/tests/t/check-cookies.t C:/projects/fortune-mod/fortune-mod/tests/t/check-rinutils.t C:/projects/fortune-mod/fortune-mod/tests/t/test-fortune-m.t C:/projects/fortune-mod/fortune-mod/tests/t/test-fortune-o-rot.t C:/projects/fortune-mod/fortune-mod/tests/t/test-fortune-percent.t C:/projects/fortune-mod/fortune-mod/tests/t/tidyall.t C:/projects/fortune-mod/fortune-mod/tests/t/trailing-space-and-CRs.t C:/projects/fortune-mod/fortune-mod/tests/t/valgrind.t]
[00:02:58] 
[00:02:58] #   Failed test 'shingeki-no-kyojin failed - Fortune cookie file contains a line longer than 78 characters.'
[00:02:58] #   at C:/projects/fortune-mod/fortune-mod/tests/t/check-cookies.t line 43.
[00:02:58] # Looks like you failed 1 test of 1.
[00:02:58] C:/projects/fortune-mod/fortune-mod/tests/t/check-cookies.t ........... 
[00:02:58] 1..1
[00:02:58] not ok 1 - shingeki-no-kyojin failed - Fortune cookie file contains a line longer than 78 characters.
[00:02:58] Dubious, test returned 1 (wstat 256, 0x100)
[00:02:58] Failed 1/1 subtests 
```

Other things:

1. Please avoid tempering with the `.gitignore`.
2. Squash the commits: https://duckduckgo.com/?q=git+squash&atb=v140-1&ia=web

Otherwise - looks good. Thanks!

**Comment by memepaleontologist2002** [comment]
I'll give you write access, and see what we can do.

**Comment by shlomif** [comment]
@memepaleontologist2002 : the diff looks good and he tests pass.thanks! Now please squash the commits into one: https://quoteinvestigator.com/2015/08/28/fish/ - "Give a Man a Fish, and You Feed Him for a Day. Teach a Man To Fish, and You Feed Him for a Lifetime".

**Comment by memepaleontologist2002** [comment]
I flooped up the rebase. 😒

**Comment by memepaleontologist2002** [comment]
I will close this PR and make a new fork.

**Pull request closed without merging**
