### PR TITLE
Reintroduce the Makefiles.

### PR DESCRIPTION
**Pull request by memepaleontologist2002**
I reintroduced the old Makefiles due to convenience purposes. People don't have to install CMake to compile it.

### CODE REVIEW

**Comment by shlomif** [comment]
Dear @memepaleontologist2002 ! Thanks for the PR, but I am much happier with the cmake and perl5-based buildsys. They are not too much to require and reintroing the makefiles will violate [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

So I have to say "no": http://shlomifishswiki.branchable.com/Never_Try_to_Please_Everyone/ . I'll give you a chance to argue your stance, though.

**Comment by memepaleontologist2002** [comment]
At least that's why forks exist!

**Comment by memepaleontologist2002** [comment]
A C++ programmer on scratch.mit.edu wanted to keep his Makefiles, I don't really blame him.

**Comment by memepaleontologist2002** [comment]
I rest my case.

**Comment by shlomif** [comment]
@memepaleontologist2002 : I think scratch is a language created by smart devs for people less smart than them: https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/selling-for-stupider-ppl.xhtml

**Pull request closed without merging**
