### PR TITLE
Support for finding fortune files from XDG_DATA_DIRS

### LINKED ISSUE #74: $XDG_DATA_DIRS and $XDG_DATA_HOME support
Would you consider adding support for looking in $XDG_DATA_DIRS and the paths listed in $XDG_DATA_HOME for fortunes? This would allow fortunes to be put in places other than the directories that are built into the binary, and allow them to use used without specifying the path to them.

Specific usecases include:
- allowing users to add their own personal fortunes and use them without needing to specify the path -- e.g. creating `~/.local/share/fortunes/myfortunes` and running `fortune myfortunes`
- adding fortunes when can't write to the default fortune dirs e.g. on multi-user systems, on systems with read-only filesystems

- more info about those vars: https://wiki.archlinux.org/title/XDG_Base_Directory#Specification
- specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I'm happy to help implement this, just kinda want your thoughts on it first before I go ahead.

### PR DESCRIPTION
**Pull request by ralismark**
Resolves #74.

This reworks support for FORTDIR/OFFDIR and LOCFORTDIR/LOCOFFDIR to support any amount of directories. I've also refactored the fortune file lookup logic to be more sensible.

---

My intention for the new lookup logic is as follows:

- If the name starts with `/` or `./` or `../`, then treat it as absolute/relative to current directory. Don't do any further processing.
- If the name ends with `-o`, strip that suffix and look in offensive dirs instead of regular fortune dirs. This matches the BSD-compatibility feature.
- For each fortune directory `<fortdir>` (out of paths in `$XDG_DATA_DIR`, FORTDIR, and LOCFORTDIR, or the corresponding offensive dirs):
  - For each language `<lang>`, try `<fortdir>/<lang>/<name>`, then try `<fortdir>/<name>`
  - Take the first one that's found, don't use all found paths.
- If still no fortune is found, try using the original name as a path relative to the current directory.

Does this look ok?

---

Remaining work:
- [ ] Localisation support
- [ ] Move XDGFORTDIR and XDGOFFDIR to CMake
- [ ] Support for probabilities for the `all` argument e.g. `fortune 9% all`

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @ralismark !

1. please keep `debugprint()`.
2. The changes are far too  intrusive. please split them into several pullreqs.

**Comment by ralismark** [comment]
Will do! I'll split this up into a few smaller standalone PRs.

**Comment by shlomif** [comment]
On Thu, 02 Mar 2023 02:22:04 -0800
Temmie Yao ***@***.***> wrote:

> Will do! I'll split this up into a few smaller standalone PRs.
> 

thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://github.com/shlomif/Freenode-programming-channel-FAQ

If Emma Watson and Arnold Schwarzenegger were locked in a room alone, only Emma
would come out alive. After she would break the door open.
    — https://www.shlomifish.org/humour/bits/facts/Emma-Watson/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
Per my earlier comments, I am closing this pullreq.

**Pull request closed without merging**
