### PR TITLE
add quote from Samo Burja "A simulacrum of reason has beaten reason"

### PR DESCRIPTION
**Pull request by rikeanimer**

### CODE REVIEW

**Comment by shlomif** [comment]
@rikeanimer : hi, thanks for the pull-req! However: the commit includes the text of a **new** file in the "build/" directory. Please rework the PR to avoid it altogether.

**Comment by rikeanimer** [comment]
omg much embarrassed ,🤦🏼‍♀️my git-jitsu skills are lacking. Roger will do. i had to do some weird squashing cause I made a spelling error etc etc and missed that.

**Comment by rikeanimer** [comment]
@shlomif ok think i got it right, let me know. 

as a side note thank you for maintaining fortune: it has been the end of my .bashrc for 2 decades and I work primarily in the shell. it makes me happy every day :) many other humans I've introduced into the ways of the shell also always put fortune at the end of their shell initialization.

**Comment by shlomif** [comment]
> @shlomif ok think i got it right, let me know.
> 
> as a side note thank you for maintaining fortune: it has been the end of my .bashrc for 2 decades and I work primarily in the shell. it makes me happy every day :) many other humans I've introduced into the ways of the shell also always put fortune at the end of their shell initialization.

You're welcome , and - thanks! That put aside: can you provide a citation for this quote?

**Comment by rikeanimer** [comment]
sure it is from Liv Boeree's longform podcast #24 where she interviews Samo Burja. I did read the contributing file and looked at recommended citation mechanisms but it was unclear if it was meta-level 3 humour.

just to be a bit philosophical I haven't found a good way to cite things on the internet that stand the test of time and tend to err on the side of not commiting stuff that [despite many claims for perma-linking etc] I've found not to work well. lol I've spent some mind cycles on this over the last three decades and frankly the only thing I've seen *actually* be stable over time is usenet forums. I've been on the webs since 1988. 

if you know of a good way to cite tell me. I can do another PR if you want me to just drop the youtube url or similar [which is https://youtu.be/A3Zd2K0BJoI?feature=shared ] but for a simple label it is 'How to Prevent Civilizational Collapse | Samo Burja | Win-Win Podcast' '[Win-Win with Liv Boeree #24]]'

lemme know what I should do. I'm happy to do things and take work off your plate.  lol prob the most stable and OSS friendlt would be to uuencode and put video on usenet and cite there

**Pull request merged**
