### PR TITLE
Update Ferengi Rules of Acquisition

### PR DESCRIPTION
**Pull request by fonic**
This pull request updates the already present _Ferengi Rules of Acquisition_ as discussed in issue #59.

The new revised set of rules is primarily based on these sources:
- https://memory-beta.fandom.com/wiki/Ferengi_Rules_of_Acquisition
- https://memory-alpha.fandom.com/wiki/Rules_of_Acquisition
- Worlds of Star Trek: Deep Space Nine - Volume 3: Ferenginar: Satisfaction is Not Guaranteed, p. 167-169 (DS9 novel)
- Star Trek Voyager Episode "False Profits" (S03E05)
- ... and many others for minor corrections

Notes:
- There are lots of rules missing. This is not an accident - AFAICT, there has never been an official, comprehensive list of all rules. There doesn't even seem to be a consensus regarding how many rules there actually are (i.e. what is the highest number)
- There are a couple of rules with the same number (e.g. rule 98, 218). Also not an accident, it seems some writers/authors did not check for collisions before making up a new rule :)
- All rules in the list are official/canon, meaning they actually appear in some form in Star Trek media (TV series, novels, comics etc.)
- The set includes a few 'inofficial' rules marked as such - those appear in Star Trek media (e.g. VOY "False Profits"), but there is no mention of a number and/or it is not clear if the rule actually is 'official' (as in sanctioned by the Ferengi government/society) or made up by certain Ferengi indiviuals

I put **a lot** of effort into this - much more than I wanted to :) I hope people like it!

### CODE REVIEW

**Comment by fonic** [comment]
By the way: the datfile is script-generated from a CSV file. Thus, if there's a need to change the format (e.g. to put double quotes around the rule text), I can still do this at this point.

**Comment by shlomif** [comment]
Hi @fonic !

> By the way: the datfile is script-generated from a CSV file. Thus, if there's a need to change the format (e.g. to put double quotes around the rule text), I can still do that at this point.

In that case, I suggest including the CSV file in the repo, along with a script to generate the datfile from it, as part of the cmake build sys. “If it's not source, it's not software.” — https://www.gnu.org/philosophy/categories.html . WDYT? Thanks!

**Comment by fonic** [comment]
Well, it's certainly possible to do that. I ported the Bash script to POSIX to eliminate Bash as a dependency (but there still might be portability issues, sed behaves quite different on some platforms like macOS).

Are you sure it's worth the effort?

Here's the script and csv file if you want to review (script has extension '.txt' to allow upload):
[froas-csv-to-dat.sh.txt](https://github.com/shlomif/fortune-mod/files/7784197/froas-csv-to-dat.sh.txt)
[froas-final.csv](https://github.com/shlomif/fortune-mod/files/7784196/froas-final.csv)

**Comment by fonic** [comment]
What is the maximum allowed line length, by the way? Test script [check-fortune-file.sh](https://github.com/shlomif/fortune-mod/blob/master/fortune-mod/tests/scripts/check-fortune-file.sh) mentions 78 characters, but actually tests for 80 characters (`egrep -q ".{81}" "$i"`).

**Comment by shlomif** [comment]
> What is the maximum allowed line length, by the way? Test script [check-fortune-file.sh](https://github.com/shlomif/fortune-mod/blob/master/fortune-mod/tests/scripts/check-fortune-file.sh) mentions 78 characters, but actually tests for 80 characters (`egrep -q ".{81}" "$i"`).

it is no longer used. see https://github.com/shlomif/fortune-mod/commit/85d55821426f2fdc8fc706da59827cb3876e634f

**Comment by shlomif** [comment]
@fonic : I added them in https://github.com/shlomif/fortune-mod/commit/aa2b6b49946390a5c98020f2dc67ff08cff9be72 . Thanks!

**Comment by fonic** [comment]
> @fonic : I added them in [aa2b6b4](https://github.com/shlomif/fortune-mod/commit/aa2b6b49946390a5c98020f2dc67ff08cff9be72) . Thanks!

**Alright, cool!** You're welcome.

Just to be sure, in case you missed my comment on that:
- I'm not 100% sure about portability of the shell script 
- The shell script generates the dat file with lines of max. 78 chars ('cause that's what I got from the now obsolete check script)

**Comment by shlomif** [comment]
Hi @fonic !

> > @fonic : I added them in [aa2b6b4](https://github.com/shlomif/fortune-mod/commit/aa2b6b49946390a5c98020f2dc67ff08cff9be72) . Thanks!
> 
> **Alright, cool!** You're welcome.
> 
> Just to be sure, in case you missed my comments on that:
> 
>     * I'm not 100% sure about portability of the generator script
> 

No worries: I'll translate it to perl or similar if it turns out to be an issue.


>     * The generator script generates datfiles with lines of 78 chars max. ('cause that's what I got from the now obsolete check script)

since 78 is less than 80, it is acceptable.

**Comment by shlomif** [comment]
Merged in a different way. Thanks!

**Comment by fonic** [comment]
> since 78 is less than 80, it is acceptable.

If you want to, just change `LINE_MAXLEN=78` in the generator script to `LINE_MAXLEN=80` and lines will be wrapped accordingly.

**Comment by shlomif** [comment]
On Tue, 28 Dec 2021 11:34:16 -0800
fonic ***@***.***> wrote:

> > since 78 is less than 80, it is acceptable.  
> 
> If you want to, just change `LINE_MAXLEN=78` in the generator script to
> `LINE_MAXLEN=80` and lines will be wrapped accordingly.
> 

Thanks! I realised that was the case.

-- 

Shlomi Fish       https://www.shlomifish.org/
Original Riddles - https://www.shlomifish.org/puzzles/

Trust in God, but tie your camel.
    — https://en.wikipedia.org/wiki/God_helps_those_who_help_themselves

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Pull request closed without merging**
