### PR TITLE
Filter out duplicate fortunes

### PR DESCRIPTION
**Pull request by inguin**
Remove two completely redundant files from off/unrotated and a large number of exact duplicates (identified by script).

### CODE REVIEW

**Comment by inguin** [comment]
Makes sense. This is the hacky Python script I used: https://gist.github.com/inguin/f4e8e5f5fb80c447527f596295edaf5a

It just reads all files into a dictionary (text -> locations), then prints those with multiple locations. Might be worth implementing as a CI test, but my Perl skills are a bit rusty.

**Comment by shlomif** [comment]
@inguin : hi! I used a tweaked version of that python3 script to create my own filtering-own changeset. can you please license your code under MITL or similar ( https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#i-want-to-release-my-code---which-open-source-licence-should-i-use ). 

commit:  https://github.com/shlomif/fortune-mod/commit/810a89e3ab46e8d224d5820104e156317fac7bdf

thanks!

**Comment by inguin** [comment]
>  can you please license your code under MITL or similar

Sure, please feel free to use the script under whichever license is best for the project.

Is that sufficient or would you like me to make a commit adding a copyright header?

**Comment by shlomif** [comment]
@inguin : thanks! I added a licence.

**Pull request closed without merging**
