### PR TITLE
Add two quotes by Linus Torvalds

### PR DESCRIPTION
**Pull request by laburnumT**

### CODE REVIEW

**Comment by laburnumT** [comment]
If requested the message-id's of the emails can be provided.

**Comment by shlomif** [comment]
@laburnumT : hi! Thanks for the pull-request!

It's quite good, but:

1. There should be links to the source posts, possibly shortened with https://is.gd/ or similar.

2. You should use "Linus Torvalds" rather than a plain "Linus" given there are other Linuses : https://en.wikipedia.org/wiki/Linus .

"Lini" ? ;)

**Comment by laburnumT** [comment]
On 2024-12-11 21:11:27, Shlomi Fish wrote:
> 1. There should be links to the source posts, possibly shortened with
> https://is.gd/ or similar.

I put in the message-id's of the emails in the commit messages as these
aren't blog posts, so a link feels a little weird. The message-id should
be usable to find the emails in whatever the lkml search archive du jour
is. I can of course pick one and use that, but there's no guarantee that
it sticks around (though lore.kernel.org will probably be ok for a
while).

If this info should be somewhere else like in the dat file that's also
possible, but I didn't see it anywhere in the other examples in the
file.

> 2. You should use "Linus Torvalds" rather than a plain "Linus" given
> there are other Linuses : https://en.wikipedia.org/wiki/Linus .

Done.


-- 
Linux: the choice of a GNU generation
		-- ***@***.*** put this on Tshirts in '93

**Comment by shlomif** [comment]
Merged, thanks!

**Pull request closed without merging**
