### PR TITLE
Improve INSTALL

### PR DESCRIPTION
**Pull request by rrthomas**
Add dependencies, fix a typo

Also add build directory to .gitignore

### CODE REVIEW

**Comment by shlomif** [comment]
Merged manually. Next time, please do not modify .gitignore .

**Comment by rrthomas** [comment]
Thanks! Should I put the change to `.gitignore` in a separate PR, then?

**Comment by shlomif** [comment]
On Fri, 12 Jan 2018 06:23:42 -0800
Reuben Thomas <notifications@github.com> wrote:

> Thanks! Should I put the change to `.gitignore` in a separate PR, then?
> 

No, please don't. Such a change will be harmful because cmake build dirs should
be preferably completely out of the src tree.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Aphorisms - http://www.shlomifish.org/humour.html

The economy depends about as much on economists as the weather does on
weather forecasters.
    — Jean-Paul Kauffmann (Unsourced, via Roman M. Parparov)

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rrthomas** [comment]
OK, then should the installation instructions be changed? They imply (`cmake ..`) that the `build` directory is a top-level subdirectory of the source tree (and that's consistent instructions for other CMake build systems I see).

**Comment by shlomif** [comment]
On Fri, 12 Jan 2018 06:58:48 -0800
Reuben Thomas <notifications@github.com> wrote:

> OK, then should the installation instructions be changed? They imply
> (`cmake ..`) that the `build` directory is a top-level subdirectory of the
> source tree (and that's consistent instructions for other CMake build systems
> I see).
> 

They dont do a lot of damage for a one-off installation run, but I guess such a
change will be OK.


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/

“Did you sleep well?”
“No, I made a couple of mistakes.”
    — https://en.wikiquote.org/wiki/Steven_Wright via Nadav Har’El

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rrthomas** [comment]
Would you like to do this? As I say, I'm familiar with the style of building in-tree, so I don't know what to suggest for a simple standard method here that will work both for developers and users who just want to install the software. (Arguably for users you might, as you say, keep the in-tree build method.)

**Comment by shlomif** [comment]
On Fri, 12 Jan 2018 09:05:13 -0800
Reuben Thomas <notifications@github.com> wrote:

> Would you like to do this? As I say, I'm familiar with the style of building
> in-tree, so I don't know what to suggest for a simple standard method here
> that will work both for developers and users who just want to install the
> software. (Arguably for users you might, as you say, keep the in-tree build
> method.)
> 

I guess I will.

Regards,



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Interview with Ben Collins-Sussman - http://shlom.in/sussman

How can you make a programming language that will be good for everything if you
cannot even make such a screwdriver?
    — An Israeli Open Source Software Enthusiast.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request closed without merging**
